name: 'On push & pull_request'
on: [push, pull_request:]
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Group of log lines
        run: |
            echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
            echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
            echo "History"
            git log --pretty=oneline
            echo "rev-list -n 1 HEAD"
            git rev-list -n 1 "HEAD"
            echo "git rev-parse "@~""
            git rev-parse "@~"
